apiVersion: v1
kind: Service
metadata:
  name: prometheus-grafana-lb
  namespace: monitoring
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "false" # Optional: public LB
  labels:
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/name: grafana
spec:
  type: LoadBalancer
  ports:
    - name: http-web
      port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/name: grafana
